[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "radlab-pii-classification"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "xlsxwriter",
    "seqeval",
    "sacremoses",
    "flask_cors",
    "ml-utils @ git+https://github.com/radlab-dev-group/ml-utils.git",
]

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
pii-classifier = "pii_classification.cli.main:main"

[tool.black]
line-length = 85
target-version = ["py310", "py311", "py312"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''